"""
Django settings for LibraryProject project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
=======
Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
<<<<<<< HEAD
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gxjemh&7-(3m=lwrw=^#fu7@qjp$xd76()logi^-gxuxx5o+-t'

# SECURITY WARNING: don't run with debug turned on in production!


# DEBUG = True


# --------------MORE SECURITY SETTING ------------  #

# Set to False for production

DEBUG = True

# Security Settings
# SECURE_BROWSER_XSS_FILTER = True
# X_FRAME_OPTIONS = 'DENY'
# SECURE_CONTENT_TYPE_NOSNIFF = True
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True

# # Redirect all HTTP requests to HTTPS
# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_PRELOAD = True
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_SECONDS = 31536000


# This configuration is important when running applications behind proxies,
# ensuring that the application correctly interprets secure requests.
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# ALLOWED_HOSTS = []

# Content Security Policy settings
# CSP_DEFAULT_SRC = ("'self'",)  # Allow content only from the same origin by default
# CSP_SCRIPT_SRC = ("'self'", "https://trustedscripts.example.com")  # Allow scripts from these sources
# CSP_STYLE_SRC = ("'self'", "https://trustedstyles.example.com")    # Allow styles from these sources
# CSP_IMG_SRC = ("'self'", "https://trustedimages.example.com")      # Allow images from these sources
# CSP_FONT_SRC = ("'self'", "https://trustedfonts.example.com")      # Allow fonts from these sources
# CSP_CONNECT_SRC = ("'self'", "https://api.example.com")            # Allow AJAX calls to these sources


=======
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9t_6g7vf!diwk4dj!8ldcp!c=4$43-g)u2y^z5!)kwxf3*-4a0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'bookshelf.apps.BookshelfConfig',
    'relationship_app.apps.RelationshipAppConfig',
    # Security setup
    # 'csp',
    # 'sslserver',
]
=======

    'bookshelf.apps.BookshelfConfig',
    'csp',
]
#Setting up User Model by specifying the model to use
AUTH_USER_MODEL = 'bookshelf.CustomUser'
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
<<<<<<< HEAD
                ],
=======
            ],
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Library',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': 'Stevengerad8!',
        'PORT': '3306',
        
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
=======
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',       
    }
}

#AUTHENTICATION SETTINGS

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/topics/i18n/
=======
# https://docs.djangoproject.com/en/5.1/topics/i18n/
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/howto/static-files/

AUTH_USER_MODEL = 'bookshelf.CustomUser'

LOGIN_REDIRECT_URL = '/'
=======
# https://docs.djangoproject.com/en/5.1/howto/static-files/
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25

STATIC_URL = 'static/'

# Default primary key field type
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
=======
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Custom Security Settings Configuration
SECURE_BROWSER_XSS_FILTER = True #enable the browser’s XSS filtering and help prevent cross-site scripting attacks.

X_FRAME_OPTIONS = 'DENY' #Prevents your site from being framed & protect against clickjacking attacks 

SECURE_CONTENT_TYPE_NOSNIFF = True #prevent browsers from MIME-sniffing a response away from the declared content-type.

CSRF_COOKIE_SECURE = True #ensure CSRF cookies are only transmitted over HTTPS.

SESSION_COOKIE_SECURE = True #ensure session cookies are only transmitted over HTTPS

SECURE_SSL_REDIRECT = True #Redirects all non-HTTPS requests to HTTPS

SECURE_HSTS_SECONDS = 31536000 #Sets HSTS to 1 year (31536000 seconds)
#Instructs browsers to only  access the site via HTTPS for the specified time

SECURE_HSTS_INCLUDE_SUBDOMAINS = True #Includes all subdomains in HSTS policy

SECURE_HSTS_PRELOAD = True #Preloads the HSTS policy in the browser

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') #Enables secure proxy support for HTTPS requests
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25
