"""
Django settings for LibraryProject project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
=======
Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
<<<<<<< HEAD
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gxjemh&7-(3m=lwrw=^#fu7@qjp$xd76()logi^-gxuxx5o+-t'
=======
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4!a@472k!ft+^!u07ri-y=sk&m=28)+ap&tdqm^wb(^(22w#_h'
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'bookshelf.apps.BookshelfConfig',
    'relationship_app.apps.RelationshipAppConfig',
=======
    'bookshelf',
    'relationship_app',
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
<<<<<<< HEAD
                ],
=======
            ],
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Library',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': 'Stevengerad8!',
        'PORT': '3306',
        
=======
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25
    }
}


# Password validation
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
=======
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/topics/i18n/
=======
# https://docs.djangoproject.com/en/5.1/topics/i18n/
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/howto/static-files/

LOGIN_REDIRECT_URL = 'login'
=======
# https://docs.djangoproject.com/en/5.1/howto/static-files/
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25

STATIC_URL = 'static/'

# Default primary key field type
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
=======
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
>>>>>>> 16dee7aeb905a470e30d02d3bea5cea76272bc25

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
